### ISSUE TITLE
баг с рюкзаками при аресте

### ISSUE THREAD

**Issue by PionerWSADnik** [alexaxel705/MTA-Tomsk#24]
после убийства остается рюкзак на месте гибели и еще с собой, тот что с собой можно выкинуть, и позже подобрать. плюс подобрать тот что остался на месте гибели и будут 2 рюкзака с одинаковым содержимым

**Comment by alexaxel705** [comment]
Исправил
https://github.com/alexaxel705/MTA-Tomsk/commit/5d519bd01e942c3d77c2a25078e1efb4e69e92ed
