### ISSUE TITLE
баг с рюкзаками 

### ISSUE THREAD

**Issue by 1miha1** [alexaxel705/MTA-Tomsk#28]
дюп вешей при помощи рюкзаков , береш один рюкзак ложиш туда какой либо предмет и меняеш его на пустой , и у тебя дюпаютца веши

**Comment by alexaxel705** [comment]
Исправил https://github.com/alexaxel705/MTA-Tomsk/commit/f76a8a53e19f21b7c8047258f97e9bafe53a121a
