### ISSUE TITLE
Сбегаем с психушки при старте...

### ISSUE THREAD

**Issue by MrQ1V1** [alexaxel705/MTA-Tomsk#29]
Заходим в чат и пишем команду «**/arm**» сервер нам предложит вступить в ряды армии ну мы же самые умные и не хотим быть психом и конечно же выбираем точку спавна в армии. А т.к мы хотим быть расхитителями сервера, то и армия нас не устраивает  поэтому мы сбегаем (становимся дезертиром), уезжаем в любой город ищем любого члена банды и вступаем в неё, делаем рестарт и воля мы не ждали пока нас выпишут, у нас есть ака-47, партроны и мы уже являемся жителями игрового сервера «**RPG RealLife (Russian Federation/Tomsk)**»

Ссылка на видео ролик о том как это можно всё сделать:
https://www.youtube.com/watch?v=IOk9T6Uo2X8

_Игровой ник: Mes'yebur_

**Comment by alexaxel705** [comment]
Исправил https://github.com/alexaxel705/MTA-Tomsk/commit/ede3352e10d3480bbec964054cfdd00d078fd0ce

**Comment by MrQ1V1** [comment]
Были обновления на основном сервере или нет? Т.к я снова смог совершить данный побег без всяких затруднений. 
https://youtu.be/DnUPBQlDMrI

**Comment by alexaxel705** [comment]
Второй патч https://github.com/alexaxel705/MTA-Tomsk/commit/60bc2fb933b50ef7e12008ad7e78bf4b696b35ff
кек, только уголовники могли служить :D
