### ISSUE TITLE
Как стать властелином пакетиков...

### ISSUE THREAD

**Issue by MrQ1V1** [alexaxel705/MTA-Tomsk#30]
Вот тут видео про то как сделать ну чутка много пакетиков, а раз можно делать пакетики то.....
https://youtu.be/obLXZMaC5x4

**Comment by alexaxel705** [comment]
Патч https://github.com/alexaxel705/MTA-Tomsk/commit/44e8bd93ca26b67991991daebf87119ca351d9cd
