### ISSUE TITLE
Из говна в высший сорт 

### ISSUE THREAD

**Issue by MrQ1V1** [alexaxel705/MTA-Tomsk#31]
Как сделать себя баронов по высшему классу качества наркоты:
https://www.youtube.com/watch?v=xza5fviok9Q
И в инвентаре чутка съехали буквы:
https://yadi.sk/i/V-DVEUmv3Jjpft

**Comment by alexaxel705** [comment]
патч https://github.com/alexaxel705/MTA-Tomsk/commit/77f5ce4c0242dce18c6a42eae19957b7ccc9a0c1
