### ISSUE TITLE
Купив мото и заехав в тюн можно и без головы остаться

### ISSUE THREAD

**Issue by MrQ1V1** [alexaxel705/MTA-Tomsk#32]
Замечал ситуацию, что в лс в тюне подкинуло мото когда я его поехал тюнить (как логично). Значение этому не придал, но вот тут один из пользователей говорит, что он настолько красиво прыгнул что помер. Проверили и оказалось, что действительно сделав себе мото в лс тюне можно неплохо сделать тп до больнички в лс. 
Видео с данными прыжками, рандом есть шансы у байкера ухаеть целым, но это лотерейка :)
https://youtu.be/a70L1FU5bbg

P.S Личная история: Я вот так уехал в лв купил байк, заехал там же в тюн и что я сделал при выходе из тюна? Да правильно, я ворвался в здание прям в текстуры... Связи с моим удачным входом в дом, я решил там и припарковать свой байк, что добру проподать :).

**Comment by alexaxel705** [comment]
Исправил https://github.com/alexaxel705/MTA-Tomsk/commit/fa3883d695ee0d2481176dd941f73e9b4869c920
