### ISSUE TITLE
Перекраска закрыта, всё хватит ей работать

### ISSUE THREAD

**Issue by MrQ1V1** [alexaxel705/MTA-Tomsk#33]
Пока писал пост про прыжки на мото в тюне, некий **[BZB]Kudim4iK** каким-то образом заехал в перекраску, там успешно был замурован и совершил великолепное тактическое действие, просто там её запарковал, теперь гараж не открывается и не откроется скорее всего больше никогда, без помощи великого разработчика т.к если сервер не багует сам, то мы создаём баги для него.
**Кусочек чатика:**
Mes'yebur: Ну она у тебя на парке точно будет
Mes'yebur: после реста, но интерессно как это так))
[BZB]Kudim4iK: я ее там и праканул
Неизвестная команда или переменная: radar
Неизвестная команда или переменная: radar
Mes'yebur: А ну збс
Mes'yebur: теперь ты сломал всё
Mes'yebur: даже после реста не откроет гараж, надо её от туда вырезать теперь)))
[BZB]Kudim4iK: ха
Mes'yebur: Тупо поломал гараж крч
[BZB]Kudim4iK: я сказочный долбаеб
Mes'yebur: Даже если её там взорвать бы получилось, она же теперь там спавнится
[BZB]Kudim4iK: мде
[BZB]Kudim4iK: сплошные баги
[BZB]Kudim4iK: ну ничего
Mes'yebur: Я могу сказать одно, ты чемпион 
[BZB]Kudim4iK: спасибо
Скринчик:
https://yadi.sk/i/VYl8rKHz3Jo3ZG

Ещё есть вопрос, посещая различные оружейные магазины бала найдена "базука", это нормально? Если же да, то всё в порядке.

**Comment by alexaxel705** [comment]
Исправил https://github.com/alexaxel705/MTA-Tomsk/commit/742db5af454a7a680836eecc2605364f1e58e715
Базука и задумана в продаже.
